version: "2"
linters:
  enable:
    - nestif
    - revive
    - wsl_v5
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/doiteng)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
