FROM node:20-alpine AS build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Serve static files with NGINX
FROM nginx:stable-alpine
# Copy the built files from Vite's 'dist' folder
COPY --from=build-stage /app/dist /usr/share/nginx/html
# Copy custom NGINX config
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]