// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/macesz/todo-go/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewTodoListStore creates a new instance of TodoListStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTodoListStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *TodoListStore {
	mock := &TodoListStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TodoListStore is an autogenerated mock type for the TodoListStore type
type TodoListStore struct {
	mock.Mock
}

type TodoListStore_Expecter struct {
	mock *mock.Mock
}

func (_m *TodoListStore) EXPECT() *TodoListStore_Expecter {
	return &TodoListStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type TodoListStore
func (_mock *TodoListStore) Create(ctx context.Context, todoList *domain.TodoList) error {
	ret := _mock.Called(ctx, todoList)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.TodoList) error); ok {
		r0 = returnFunc(ctx, todoList)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TodoListStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TodoListStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - todoList *domain.TodoList
func (_e *TodoListStore_Expecter) Create(ctx interface{}, todoList interface{}) *TodoListStore_Create_Call {
	return &TodoListStore_Create_Call{Call: _e.mock.On("Create", ctx, todoList)}
}

func (_c *TodoListStore_Create_Call) Run(run func(ctx context.Context, todoList *domain.TodoList)) *TodoListStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.TodoList
		if args[1] != nil {
			arg1 = args[1].(*domain.TodoList)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TodoListStore_Create_Call) Return(err error) *TodoListStore_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TodoListStore_Create_Call) RunAndReturn(run func(ctx context.Context, todoList *domain.TodoList) error) *TodoListStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type TodoListStore
func (_mock *TodoListStore) Delete(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TodoListStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type TodoListStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *TodoListStore_Expecter) Delete(ctx interface{}, id interface{}) *TodoListStore_Delete_Call {
	return &TodoListStore_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *TodoListStore_Delete_Call) Run(run func(ctx context.Context, id int64)) *TodoListStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TodoListStore_Delete_Call) Return(err error) *TodoListStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TodoListStore_Delete_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *TodoListStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetListByID provides a mock function for the type TodoListStore
func (_mock *TodoListStore) GetListByID(ctx context.Context, id int64) (*domain.TodoList, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetListByID")
	}

	var r0 *domain.TodoList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*domain.TodoList, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *domain.TodoList); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TodoList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TodoListStore_GetListByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetListByID'
type TodoListStore_GetListByID_Call struct {
	*mock.Call
}

// GetListByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *TodoListStore_Expecter) GetListByID(ctx interface{}, id interface{}) *TodoListStore_GetListByID_Call {
	return &TodoListStore_GetListByID_Call{Call: _e.mock.On("GetListByID", ctx, id)}
}

func (_c *TodoListStore_GetListByID_Call) Run(run func(ctx context.Context, id int64)) *TodoListStore_GetListByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TodoListStore_GetListByID_Call) Return(todoList *domain.TodoList, err error) *TodoListStore_GetListByID_Call {
	_c.Call.Return(todoList, err)
	return _c
}

func (_c *TodoListStore_GetListByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (*domain.TodoList, error)) *TodoListStore_GetListByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type TodoListStore
func (_mock *TodoListStore) List(ctx context.Context, userId int64) ([]*domain.TodoList, error) {
	ret := _mock.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.TodoList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]*domain.TodoList, error)); ok {
		return returnFunc(ctx, userId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []*domain.TodoList); ok {
		r0 = returnFunc(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.TodoList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TodoListStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type TodoListStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userId int64
func (_e *TodoListStore_Expecter) List(ctx interface{}, userId interface{}) *TodoListStore_List_Call {
	return &TodoListStore_List_Call{Call: _e.mock.On("List", ctx, userId)}
}

func (_c *TodoListStore_List_Call) Run(run func(ctx context.Context, userId int64)) *TodoListStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TodoListStore_List_Call) Return(todoLists []*domain.TodoList, err error) *TodoListStore_List_Call {
	_c.Call.Return(todoLists, err)
	return _c
}

func (_c *TodoListStore_List_Call) RunAndReturn(run func(ctx context.Context, userId int64) ([]*domain.TodoList, error)) *TodoListStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type TodoListStore
func (_mock *TodoListStore) Update(ctx context.Context, id int64, title string, color string, labels []string) (*domain.TodoList, error) {
	ret := _mock.Called(ctx, id, title, color, labels)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.TodoList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string, []string) (*domain.TodoList, error)); ok {
		return returnFunc(ctx, id, title, color, labels)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string, []string) *domain.TodoList); ok {
		r0 = returnFunc(ctx, id, title, color, labels)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TodoList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string, string, []string) error); ok {
		r1 = returnFunc(ctx, id, title, color, labels)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TodoListStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type TodoListStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - title string
//   - color string
//   - labels []string
func (_e *TodoListStore_Expecter) Update(ctx interface{}, id interface{}, title interface{}, color interface{}, labels interface{}) *TodoListStore_Update_Call {
	return &TodoListStore_Update_Call{Call: _e.mock.On("Update", ctx, id, title, color, labels)}
}

func (_c *TodoListStore_Update_Call) Run(run func(ctx context.Context, id int64, title string, color string, labels []string)) *TodoListStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []string
		if args[4] != nil {
			arg4 = args[4].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *TodoListStore_Update_Call) Return(todoList *domain.TodoList, err error) *TodoListStore_Update_Call {
	_c.Call.Return(todoList, err)
	return _c
}

func (_c *TodoListStore_Update_Call) RunAndReturn(run func(ctx context.Context, id int64, title string, color string, labels []string) (*domain.TodoList, error)) *TodoListStore_Update_Call {
	_c.Call.Return(run)
	return _c
}
