// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/macesz/todo-go/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewTodoStore creates a new instance of TodoStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTodoStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *TodoStore {
	mock := &TodoStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TodoStore is an autogenerated mock type for the TodoStore type
type TodoStore struct {
	mock.Mock
}

type TodoStore_Expecter struct {
	mock *mock.Mock
}

func (_m *TodoStore) EXPECT() *TodoStore_Expecter {
	return &TodoStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type TodoStore
func (_mock *TodoStore) Create(ctx context.Context, listID int64, todo *domain.Todo) error {
	ret := _mock.Called(ctx, listID, todo)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *domain.Todo) error); ok {
		r0 = returnFunc(ctx, listID, todo)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TodoStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TodoStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - listID int64
//   - todo *domain.Todo
func (_e *TodoStore_Expecter) Create(ctx interface{}, listID interface{}, todo interface{}) *TodoStore_Create_Call {
	return &TodoStore_Create_Call{Call: _e.mock.On("Create", ctx, listID, todo)}
}

func (_c *TodoStore_Create_Call) Run(run func(ctx context.Context, listID int64, todo *domain.Todo)) *TodoStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 *domain.Todo
		if args[2] != nil {
			arg2 = args[2].(*domain.Todo)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TodoStore_Create_Call) Return(err error) *TodoStore_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TodoStore_Create_Call) RunAndReturn(run func(ctx context.Context, listID int64, todo *domain.Todo) error) *TodoStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type TodoStore
func (_mock *TodoStore) Delete(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TodoStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type TodoStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *TodoStore_Expecter) Delete(ctx interface{}, id interface{}) *TodoStore_Delete_Call {
	return &TodoStore_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *TodoStore_Delete_Call) Run(run func(ctx context.Context, id int64)) *TodoStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TodoStore_Delete_Call) Return(err error) *TodoStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TodoStore_Delete_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *TodoStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type TodoStore
func (_mock *TodoStore) Get(ctx context.Context, id int64) (*domain.Todo, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*domain.Todo, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *domain.Todo); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TodoStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type TodoStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *TodoStore_Expecter) Get(ctx interface{}, id interface{}) *TodoStore_Get_Call {
	return &TodoStore_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *TodoStore_Get_Call) Run(run func(ctx context.Context, id int64)) *TodoStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TodoStore_Get_Call) Return(todo *domain.Todo, err error) *TodoStore_Get_Call {
	_c.Call.Return(todo, err)
	return _c
}

func (_c *TodoStore_Get_Call) RunAndReturn(run func(ctx context.Context, id int64) (*domain.Todo, error)) *TodoStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type TodoStore
func (_mock *TodoStore) List(ctx context.Context, userID int64, listID int64) ([]*domain.Todo, error) {
	ret := _mock.Called(ctx, userID, listID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) ([]*domain.Todo, error)); ok {
		return returnFunc(ctx, userID, listID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) []*domain.Todo); ok {
		r0 = returnFunc(ctx, userID, listID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, userID, listID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TodoStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type TodoStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - listID int64
func (_e *TodoStore_Expecter) List(ctx interface{}, userID interface{}, listID interface{}) *TodoStore_List_Call {
	return &TodoStore_List_Call{Call: _e.mock.On("List", ctx, userID, listID)}
}

func (_c *TodoStore_List_Call) Run(run func(ctx context.Context, userID int64, listID int64)) *TodoStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TodoStore_List_Call) Return(todos []*domain.Todo, err error) *TodoStore_List_Call {
	_c.Call.Return(todos, err)
	return _c
}

func (_c *TodoStore_List_Call) RunAndReturn(run func(ctx context.Context, userID int64, listID int64) ([]*domain.Todo, error)) *TodoStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type TodoStore
func (_mock *TodoStore) Update(ctx context.Context, id int64, title string, done bool, priority int64) (*domain.Todo, error) {
	ret := _mock.Called(ctx, id, title, done, priority)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, bool, int64) (*domain.Todo, error)); ok {
		return returnFunc(ctx, id, title, done, priority)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, bool, int64) *domain.Todo); ok {
		r0 = returnFunc(ctx, id, title, done, priority)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string, bool, int64) error); ok {
		r1 = returnFunc(ctx, id, title, done, priority)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TodoStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type TodoStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - title string
//   - done bool
//   - priority int64
func (_e *TodoStore_Expecter) Update(ctx interface{}, id interface{}, title interface{}, done interface{}, priority interface{}) *TodoStore_Update_Call {
	return &TodoStore_Update_Call{Call: _e.mock.On("Update", ctx, id, title, done, priority)}
}

func (_c *TodoStore_Update_Call) Run(run func(ctx context.Context, id int64, title string, done bool, priority int64)) *TodoStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *TodoStore_Update_Call) Return(todo *domain.Todo, err error) *TodoStore_Update_Call {
	_c.Call.Return(todo, err)
	return _c
}

func (_c *TodoStore_Update_Call) RunAndReturn(run func(ctx context.Context, id int64, title string, done bool, priority int64) (*domain.Todo, error)) *TodoStore_Update_Call {
	_c.Call.Return(run)
	return _c
}
