// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/macesz/todo-go/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewTodoService creates a new instance of TodoService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTodoService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TodoService {
	mock := &TodoService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TodoService is an autogenerated mock type for the TodoService type
type TodoService struct {
	mock.Mock
}

type TodoService_Expecter struct {
	mock *mock.Mock
}

func (_m *TodoService) EXPECT() *TodoService_Expecter {
	return &TodoService_Expecter{mock: &_m.Mock}
}

// CreateTodo provides a mock function for the type TodoService
func (_mock *TodoService) CreateTodo(ctx context.Context, title string) (domain.Todo, error) {
	ret := _mock.Called(ctx, title)

	if len(ret) == 0 {
		panic("no return value specified for CreateTodo")
	}

	var r0 domain.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.Todo, error)); ok {
		return returnFunc(ctx, title)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.Todo); ok {
		r0 = returnFunc(ctx, title)
	} else {
		r0 = ret.Get(0).(domain.Todo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, title)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TodoService_CreateTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTodo'
type TodoService_CreateTodo_Call struct {
	*mock.Call
}

// CreateTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - title string
func (_e *TodoService_Expecter) CreateTodo(ctx interface{}, title interface{}) *TodoService_CreateTodo_Call {
	return &TodoService_CreateTodo_Call{Call: _e.mock.On("CreateTodo", ctx, title)}
}

func (_c *TodoService_CreateTodo_Call) Run(run func(ctx context.Context, title string)) *TodoService_CreateTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TodoService_CreateTodo_Call) Return(todo domain.Todo, err error) *TodoService_CreateTodo_Call {
	_c.Call.Return(todo, err)
	return _c
}

func (_c *TodoService_CreateTodo_Call) RunAndReturn(run func(ctx context.Context, title string) (domain.Todo, error)) *TodoService_CreateTodo_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTodo provides a mock function for the type TodoService
func (_mock *TodoService) DeleteTodo(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTodo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TodoService_DeleteTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTodo'
type TodoService_DeleteTodo_Call struct {
	*mock.Call
}

// DeleteTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *TodoService_Expecter) DeleteTodo(ctx interface{}, id interface{}) *TodoService_DeleteTodo_Call {
	return &TodoService_DeleteTodo_Call{Call: _e.mock.On("DeleteTodo", ctx, id)}
}

func (_c *TodoService_DeleteTodo_Call) Run(run func(ctx context.Context, id int)) *TodoService_DeleteTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TodoService_DeleteTodo_Call) Return(err error) *TodoService_DeleteTodo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TodoService_DeleteTodo_Call) RunAndReturn(run func(ctx context.Context, id int) error) *TodoService_DeleteTodo_Call {
	_c.Call.Return(run)
	return _c
}

// GetTodo provides a mock function for the type TodoService
func (_mock *TodoService) GetTodo(ctx context.Context, id int) (domain.Todo, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTodo")
	}

	var r0 domain.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (domain.Todo, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) domain.Todo); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Todo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TodoService_GetTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTodo'
type TodoService_GetTodo_Call struct {
	*mock.Call
}

// GetTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *TodoService_Expecter) GetTodo(ctx interface{}, id interface{}) *TodoService_GetTodo_Call {
	return &TodoService_GetTodo_Call{Call: _e.mock.On("GetTodo", ctx, id)}
}

func (_c *TodoService_GetTodo_Call) Run(run func(ctx context.Context, id int)) *TodoService_GetTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TodoService_GetTodo_Call) Return(todo domain.Todo, err error) *TodoService_GetTodo_Call {
	_c.Call.Return(todo, err)
	return _c
}

func (_c *TodoService_GetTodo_Call) RunAndReturn(run func(ctx context.Context, id int) (domain.Todo, error)) *TodoService_GetTodo_Call {
	_c.Call.Return(run)
	return _c
}

// ListTodos provides a mock function for the type TodoService
func (_mock *TodoService) ListTodos(ctx context.Context) ([]domain.Todo, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTodos")
	}

	var r0 []domain.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.Todo, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.Todo); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TodoService_ListTodos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTodos'
type TodoService_ListTodos_Call struct {
	*mock.Call
}

// ListTodos is a helper method to define mock.On call
//   - ctx context.Context
func (_e *TodoService_Expecter) ListTodos(ctx interface{}) *TodoService_ListTodos_Call {
	return &TodoService_ListTodos_Call{Call: _e.mock.On("ListTodos", ctx)}
}

func (_c *TodoService_ListTodos_Call) Run(run func(ctx context.Context)) *TodoService_ListTodos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TodoService_ListTodos_Call) Return(todos []domain.Todo, err error) *TodoService_ListTodos_Call {
	_c.Call.Return(todos, err)
	return _c
}

func (_c *TodoService_ListTodos_Call) RunAndReturn(run func(ctx context.Context) ([]domain.Todo, error)) *TodoService_ListTodos_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTodo provides a mock function for the type TodoService
func (_mock *TodoService) UpdateTodo(ctx context.Context, id int, title string, done bool) (domain.Todo, error) {
	ret := _mock.Called(ctx, id, title, done)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTodo")
	}

	var r0 domain.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, bool) (domain.Todo, error)); ok {
		return returnFunc(ctx, id, title, done)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, bool) domain.Todo); ok {
		r0 = returnFunc(ctx, id, title, done)
	} else {
		r0 = ret.Get(0).(domain.Todo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, string, bool) error); ok {
		r1 = returnFunc(ctx, id, title, done)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TodoService_UpdateTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTodo'
type TodoService_UpdateTodo_Call struct {
	*mock.Call
}

// UpdateTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - title string
//   - done bool
func (_e *TodoService_Expecter) UpdateTodo(ctx interface{}, id interface{}, title interface{}, done interface{}) *TodoService_UpdateTodo_Call {
	return &TodoService_UpdateTodo_Call{Call: _e.mock.On("UpdateTodo", ctx, id, title, done)}
}

func (_c *TodoService_UpdateTodo_Call) Run(run func(ctx context.Context, id int, title string, done bool)) *TodoService_UpdateTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *TodoService_UpdateTodo_Call) Return(todo domain.Todo, err error) *TodoService_UpdateTodo_Call {
	_c.Call.Return(todo, err)
	return _c
}

func (_c *TodoService_UpdateTodo_Call) RunAndReturn(run func(ctx context.Context, id int, title string, done bool) (domain.Todo, error)) *TodoService_UpdateTodo_Call {
	_c.Call.Return(run)
	return _c
}
