// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/macesz/todo-go/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewUserStore creates a new instance of UserStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserStore {
	mock := &UserStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserStore is an autogenerated mock type for the UserStore type
type UserStore struct {
	mock.Mock
}

type UserStore_Expecter struct {
	mock *mock.Mock
}

func (_m *UserStore) EXPECT() *UserStore_Expecter {
	return &UserStore_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type UserStore
func (_mock *UserStore) CreateUser(ctx context.Context, user *domain.User) (*domain.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.User) (*domain.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.User) *domain.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserStore_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type UserStore_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *domain.User
func (_e *UserStore_Expecter) CreateUser(ctx interface{}, user interface{}) *UserStore_CreateUser_Call {
	return &UserStore_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *UserStore_CreateUser_Call) Run(run func(ctx context.Context, user *domain.User)) *UserStore_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.User
		if args[1] != nil {
			arg1 = args[1].(*domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserStore_CreateUser_Call) Return(user1 *domain.User, err error) *UserStore_CreateUser_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *UserStore_CreateUser_Call) RunAndReturn(run func(ctx context.Context, user *domain.User) (*domain.User, error)) *UserStore_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type UserStore
func (_mock *UserStore) DeleteUser(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserStore_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type UserStore_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *UserStore_Expecter) DeleteUser(ctx interface{}, id interface{}) *UserStore_DeleteUser_Call {
	return &UserStore_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, id)}
}

func (_c *UserStore_DeleteUser_Call) Run(run func(ctx context.Context, id int64)) *UserStore_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserStore_DeleteUser_Call) Return(err error) *UserStore_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserStore_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *UserStore_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type UserStore
func (_mock *UserStore) GetUser(ctx context.Context, id int64) (*domain.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*domain.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *domain.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserStore_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type UserStore_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *UserStore_Expecter) GetUser(ctx interface{}, id interface{}) *UserStore_GetUser_Call {
	return &UserStore_GetUser_Call{Call: _e.mock.On("GetUser", ctx, id)}
}

func (_c *UserStore_GetUser_Call) Run(run func(ctx context.Context, id int64)) *UserStore_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserStore_GetUser_Call) Return(user *domain.User, err error) *UserStore_GetUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserStore_GetUser_Call) RunAndReturn(run func(ctx context.Context, id int64) (*domain.User, error)) *UserStore_GetUser_Call {
	_c.Call.Return(run)
	return _c
}
