// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/macesz/todo-go/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewTodoListService creates a new instance of TodoListService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTodoListService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TodoListService {
	mock := &TodoListService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TodoListService is an autogenerated mock type for the TodoListService type
type TodoListService struct {
	mock.Mock
}

type TodoListService_Expecter struct {
	mock *mock.Mock
}

func (_m *TodoListService) EXPECT() *TodoListService_Expecter {
	return &TodoListService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type TodoListService
func (_mock *TodoListService) Create(ctx context.Context, userID int64, title string, color string, labels []string) (*domain.TodoList, error) {
	ret := _mock.Called(ctx, userID, title, color, labels)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.TodoList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string, []string) (*domain.TodoList, error)); ok {
		return returnFunc(ctx, userID, title, color, labels)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string, []string) *domain.TodoList); ok {
		r0 = returnFunc(ctx, userID, title, color, labels)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TodoList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string, string, []string) error); ok {
		r1 = returnFunc(ctx, userID, title, color, labels)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TodoListService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TodoListService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - title string
//   - color string
//   - labels []string
func (_e *TodoListService_Expecter) Create(ctx interface{}, userID interface{}, title interface{}, color interface{}, labels interface{}) *TodoListService_Create_Call {
	return &TodoListService_Create_Call{Call: _e.mock.On("Create", ctx, userID, title, color, labels)}
}

func (_c *TodoListService_Create_Call) Run(run func(ctx context.Context, userID int64, title string, color string, labels []string)) *TodoListService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []string
		if args[4] != nil {
			arg4 = args[4].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *TodoListService_Create_Call) Return(todoList *domain.TodoList, err error) *TodoListService_Create_Call {
	_c.Call.Return(todoList, err)
	return _c
}

func (_c *TodoListService_Create_Call) RunAndReturn(run func(ctx context.Context, userID int64, title string, color string, labels []string) (*domain.TodoList, error)) *TodoListService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type TodoListService
func (_mock *TodoListService) Delete(ctx context.Context, userID int64, id int64) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TodoListService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type TodoListService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
func (_e *TodoListService_Expecter) Delete(ctx interface{}, userID interface{}, id interface{}) *TodoListService_Delete_Call {
	return &TodoListService_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, id)}
}

func (_c *TodoListService_Delete_Call) Run(run func(ctx context.Context, userID int64, id int64)) *TodoListService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TodoListService_Delete_Call) Return(err error) *TodoListService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TodoListService_Delete_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64) error) *TodoListService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetListByID provides a mock function for the type TodoListService
func (_mock *TodoListService) GetListByID(ctx context.Context, userID int64, id int64) (*domain.TodoList, error) {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetListByID")
	}

	var r0 *domain.TodoList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) (*domain.TodoList, error)); ok {
		return returnFunc(ctx, userID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) *domain.TodoList); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TodoList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TodoListService_GetListByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetListByID'
type TodoListService_GetListByID_Call struct {
	*mock.Call
}

// GetListByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
func (_e *TodoListService_Expecter) GetListByID(ctx interface{}, userID interface{}, id interface{}) *TodoListService_GetListByID_Call {
	return &TodoListService_GetListByID_Call{Call: _e.mock.On("GetListByID", ctx, userID, id)}
}

func (_c *TodoListService_GetListByID_Call) Run(run func(ctx context.Context, userID int64, id int64)) *TodoListService_GetListByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TodoListService_GetListByID_Call) Return(todoList *domain.TodoList, err error) *TodoListService_GetListByID_Call {
	_c.Call.Return(todoList, err)
	return _c
}

func (_c *TodoListService_GetListByID_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64) (*domain.TodoList, error)) *TodoListService_GetListByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type TodoListService
func (_mock *TodoListService) List(ctx context.Context, userID int64) ([]*domain.TodoList, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.TodoList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]*domain.TodoList, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []*domain.TodoList); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.TodoList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TodoListService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type TodoListService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *TodoListService_Expecter) List(ctx interface{}, userID interface{}) *TodoListService_List_Call {
	return &TodoListService_List_Call{Call: _e.mock.On("List", ctx, userID)}
}

func (_c *TodoListService_List_Call) Run(run func(ctx context.Context, userID int64)) *TodoListService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TodoListService_List_Call) Return(todoLists []*domain.TodoList, err error) *TodoListService_List_Call {
	_c.Call.Return(todoLists, err)
	return _c
}

func (_c *TodoListService_List_Call) RunAndReturn(run func(ctx context.Context, userID int64) ([]*domain.TodoList, error)) *TodoListService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type TodoListService
func (_mock *TodoListService) Update(ctx context.Context, userID int64, id int64, title string, color string, labels []string) (*domain.TodoList, error) {
	ret := _mock.Called(ctx, userID, id, title, color, labels)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.TodoList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, string, string, []string) (*domain.TodoList, error)); ok {
		return returnFunc(ctx, userID, id, title, color, labels)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, string, string, []string) *domain.TodoList); ok {
		r0 = returnFunc(ctx, userID, id, title, color, labels)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TodoList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64, string, string, []string) error); ok {
		r1 = returnFunc(ctx, userID, id, title, color, labels)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TodoListService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type TodoListService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
//   - title string
//   - color string
//   - labels []string
func (_e *TodoListService_Expecter) Update(ctx interface{}, userID interface{}, id interface{}, title interface{}, color interface{}, labels interface{}) *TodoListService_Update_Call {
	return &TodoListService_Update_Call{Call: _e.mock.On("Update", ctx, userID, id, title, color, labels)}
}

func (_c *TodoListService_Update_Call) Run(run func(ctx context.Context, userID int64, id int64, title string, color string, labels []string)) *TodoListService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 []string
		if args[5] != nil {
			arg5 = args[5].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *TodoListService_Update_Call) Return(todoList *domain.TodoList, err error) *TodoListService_Update_Call {
	_c.Call.Return(todoList, err)
	return _c
}

func (_c *TodoListService_Update_Call) RunAndReturn(run func(ctx context.Context, userID int64, id int64, title string, color string, labels []string) (*domain.TodoList, error)) *TodoListService_Update_Call {
	_c.Call.Return(run)
	return _c
}
