// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/macesz/todo-go/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewTodoService creates a new instance of TodoService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTodoService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TodoService {
	mock := &TodoService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TodoService is an autogenerated mock type for the TodoService type
type TodoService struct {
	mock.Mock
}

type TodoService_Expecter struct {
	mock *mock.Mock
}

func (_m *TodoService) EXPECT() *TodoService_Expecter {
	return &TodoService_Expecter{mock: &_m.Mock}
}

// ListTodos provides a mock function for the type TodoService
func (_mock *TodoService) ListTodos(ctx context.Context, userID int64, todolistID int64) ([]*domain.Todo, error) {
	ret := _mock.Called(ctx, userID, todolistID)

	if len(ret) == 0 {
		panic("no return value specified for ListTodos")
	}

	var r0 []*domain.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) ([]*domain.Todo, error)); ok {
		return returnFunc(ctx, userID, todolistID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) []*domain.Todo); ok {
		r0 = returnFunc(ctx, userID, todolistID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, userID, todolistID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TodoService_ListTodos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTodos'
type TodoService_ListTodos_Call struct {
	*mock.Call
}

// ListTodos is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - todolistID int64
func (_e *TodoService_Expecter) ListTodos(ctx interface{}, userID interface{}, todolistID interface{}) *TodoService_ListTodos_Call {
	return &TodoService_ListTodos_Call{Call: _e.mock.On("ListTodos", ctx, userID, todolistID)}
}

func (_c *TodoService_ListTodos_Call) Run(run func(ctx context.Context, userID int64, todolistID int64)) *TodoService_ListTodos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TodoService_ListTodos_Call) Return(todos []*domain.Todo, err error) *TodoService_ListTodos_Call {
	_c.Call.Return(todos, err)
	return _c
}

func (_c *TodoService_ListTodos_Call) RunAndReturn(run func(ctx context.Context, userID int64, todolistID int64) ([]*domain.Todo, error)) *TodoService_ListTodos_Call {
	_c.Call.Return(run)
	return _c
}
